# permissions for end users to view slodescs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slodesc-viewer-role
rules:
- apiGroups:
  - slo.ibm.com
  resources:
  - slodescs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slo.ibm.com
  resources:
  - slodescs/status
  verbs:
  - get
