apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: kcontainer
spec:
  template:
    spec:
      containers:
      - image: docker.io/serverlessslo/helloworld
        env:
        - name: TARGET
          value: "Helow world from Knative serving"